### ISSUE TITLE
 Manage conference participations (as admin, as user)

### ISSUE THREAD

**Issue by welcoMattic** [jolicode/starfleet#8]
As an admin, I want to see the conferences that users are interested in, the ones they ask to attend. They can request to participate, then I could validate or reject these requests.

Once the request has been validated, I can indicate the status of the next steps: transport tickets, hotel booking, conference tickets...

A participation request can be opened by any user, but if they got a pending submission or they are speaker to the conference, they *must* mention it in the request (checkbox for it).

Each user will have statistics on his participations/submissions (accepted and rejected). These statistics will be displayed to admin, to let theme decide to accept or reject requests.

**Comment by damienalexandre** [comment]
It should also be clear for the admin what is the requester status:

- did he respond to the CFP of that conference?
- did he got selected and is a speaker?
- an easy access to the conference the user has been and is planned to go.
