### ISSUE TITLE
Improve Talks list view on admin

### ISSUE THREAD

**Issue by welcoMattic** [jolicode/starfleet#85]
The actual talks list view is very "empty"
![image](https://user-images.githubusercontent.com/773875/100237901-d47f1a00-2f2f-11eb-8944-ec275cafd646.png)

It should be great to add some columns like "authors", "created at", … In this way, it will be possible to filter on these fields to easily retrieve Talks.

**Comment by lyrixx** [comment]
We **might** use https://github.com/alterphp/EasyAdminExtensionBundle
