### ISSUE TITLE
Foreign key violation when deleting a user or a conference

### ISSUE THREAD

**Issue by HedicGuibert** [jolicode/starfleet#93]
There is a bug when trying to delete a user or a conference in Easy Admin.

If you try to delete a user, the foreign key of that user is still referenced in the participation table, raising this exception :
![User Exception](https://user-images.githubusercontent.com/71645693/102241059-d9186c00-3ef8-11eb-9ec7-a9feba97eea9.png)

The same occurs with some conferences, but not all of them (I don't know why, it may be because of the fixtures), because the key is still referenced in the submit table.

A quick solution would be to remove the possibility to delete a user or a conference in the admin, but ultimately a decision should should be taken about whether or not we want to completely remove all participations of deleted users. Same goes with conferences : if we delete a conference, do we want to delete all submits referencing this conference ?

**Comment by welcoMattic** [comment]
Good catch! May be it's time to implement soft delete or archive for users and conferences? It could be relevant because the organization could want to keep the history of all users and and therefore the associated conferences.

**Comment by lyrixx** [comment]
@welcoMattic It's your project, you have to take a decision :) 
Personally, If we could avoid soft delete, I would! (GDRP at least)
Instead I would "SET NULL" where needed. And of course, the frontend would be update everywhere we display a username

**Comment by welcoMattic** [comment]
I'm not sure that we should worry about GDPR as Starfleet can be installed by everyone. But, ok let's assume it's better to provide à GDPR compliant software ;)
Ok to "SET NULL" where needed and adapt the frontend :+1:

**Comment by lyrixx** [comment]
The more I think about it, the less I understand it. IMHO this does not make sense to remove a conference when people attend to it or when a submission has been made. I would forbid such action. 

@welcoMattic wdyt ?

**Comment by welcoMattic** [comment]
Indeed, I agree to forbid the deletion of conferences. As most of the time they are automatically created by fetchers, and not manually. Let's forbid this action, and if it's annoying in the future, we will work back on it.
